import { Form, Formik, type FormikHelpers } from "formik";
import { Collapsible as C } from "radix-ui";
import { useState } from "react";
import { CoordinateStringOptionsForm } from "@/components/coordinate_string_options_form";
import * as E from "@/components/elements";
import { SelectFileType } from "@/components/fields";
import { CsvOptionsForm, XlsOptionsForm } from "@/features/csv_options_form";
import { useImportFile } from "@/hooks/use_import";
import {
  DEFAULT_IMPORT_OPTIONS,
  type ImportOptions,
  type Progress,
} from "@/utils/convert";
import type { FileGroup } from "@/utils/group_files";
import { AutoDetect } from "../autodetect";
import type { OnNext } from "../import";
import SimpleDialogActions from "../simple_dialog_actions";
import { FileWarning } from "./file_warning";
import { ImportProgressBar } from "./import_progress_bar";

type SecondaryAction = React.ComponentProps<
  typeof SimpleDialogActions
>["secondary"];

function GeoJSONOptionsForm() {
  return (
    <C.Root>
      <C.Trigger asChild>
        <E.Button size="xs">Advanced options</E.Button>
      </C.Trigger>

      <C.Content className="space-y-2 pl-2 pt-4">
        <div className="space-y-1">
          <label className="flex items-center">
            <E.FieldCheckbox type="checkbox" name="removeCoincidents" />
            <div className="pl-2 text-sm">Remove coincident vertices</div>
          </label>
          <E.TextWell>
            Removes consecutive vertices with the same coordinate values that
            can be generated by other tools.
          </E.TextWell>
        </div>
      </C.Content>
    </C.Root>
  );
}

export function ImportFileGroup({
  onNext,
  hasNext,
  onClose,
  secondary,
  file: fileGroup,
}: {
  onNext: OnNext;
  hasNext: boolean;
  onClose: () => void;
  secondary: SecondaryAction;
  file: FileGroup;
}) {
  const { file } = fileGroup;
  const doImport = useImportFile();
  const [progress, setProgress] = useState<Progress | null>(null);

  return (
    <Formik
      onSubmit={async function onSubmit(
        options: ImportOptions,
        helpers: FormikHelpers<ImportOptions>,
      ) {
        try {
          options = { ...options, toast: !hasNext };
          const res = await doImport(file, options, (newProgress) => {
            setProgress(newProgress);
          });
          res.caseOf({
            Left(err) {
              setProgress(null);
              helpers.setErrors({ type: err.message });
            },
            Right: async (r) => {
              return onNext(await r);
            },
          });
        } catch (e: any) {
          helpers.setErrors({
            type: e.message,
          });
        }
      }}
      initialValues={{
        ...DEFAULT_IMPORT_OPTIONS,
        type: "geojson",
        text: "",
        toast: true,
        secondary: false,
      }}
    >
      <Form>
        <div>
          <div className="space-y-4">
            <SelectFileType />
            <CoordinateStringOptionsForm />
            <CsvOptionsForm file={file} geocoder />
            <GeoJSONOptionsForm />
            <XlsOptionsForm file={file} geocoder />
          </div>
          <FileWarning file={fileGroup}>
            <SimpleDialogActions
              secondary={secondary}
              onClose={onClose}
              action="Import"
            />
          </FileWarning>
          <ImportProgressBar progress={progress} />
        </div>
        <AutoDetect file={file} />
      </Form>
    </Formik>
  );
}
